### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by efatmae** [richardsun-voyager/understanding_attention_for_text_classification#1]
Hi,
I read your paper and I think it is very interesting work. Thanks for sharing the code on GitHub. I pulled the project and ran it. I have a question regarding the dataset. you use embedded vectors as pkl files. Can you tell me which embedding method have you used? word2vec or something else?

Thanks,
Fatma

**Comment by richardsun-voyager** [comment]
Hi Fatma, 
Thanks for your attention. Actually, we did not use any pre-trained embeddings in our main work. We expected to observe certain patterns captured by the model on the training set without the influence of any prior information.
 But we ran experiments with **[Glove](https://nlp.stanford.edu/projects/glove/)** in our supplementary materials. We are still refining the supplementary material and will upload it very soon. I'll keep you updated once it is uploaded.
Feel free to contact me if any questions.
Best,
Richard

**Comment by efatmae** [comment]
Thanks for your reply.
Can you then tell me how you generated the pick files in the dataset folder?

Best,
Fatma

**Comment by richardsun-voyager** [comment]
Hi Fatma,
We selected the corresponding embedding from Glove for each token in our SST dataset, then converted the selected embeddings into a binary format using the [pickle](https://docs.python.org/3/library/pickle.html) package.
We uploaded the preprocessing code.
Hope this can answer your question!
Best,
Richard
