### ISSUE TITLE
How to derive the gradient of **e** in the paper

### ISSUE THREAD

**Issue by Riroaki** [richardsun-voyager/understanding_attention_for_text_classification#4]
Hi, I am interested in your work but having some trouble with the derivation of the gradient of word embedding **e** in your paper. I didn't find any proof or deriving process in this `supplementary material` as is stated in the paper though, would you kindly publish it here?

**Comment by richardsun-voyager** [comment]
Hi Riroaki, thanks for your interest. I have uploaded the derivatives. Could you check it again please?

**Comment by Riroaki** [comment]
Thanks! Neat work:)
